# Generated by Django 5.2.14 on 2026-08-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockup',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='colors',
            field=models.JSONField(default=list, help_text='[{"name": "Black", "pantone": "19-0303"}]'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mockup_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
